name: Test
on:
  push:
    branches: ['master']
  pull_request: ~
permissions:
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Validate composer.json and composer.lock
      run: composer validate --strict
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
    - name: PHPStan
      run: composer run-script phpstan
    - name: Pest
      run: composer run-script pest
